services:
  nestjs:
    container_name: nestjs
    build: ./
    ports:
      - '80:3001'
    networks:
      - app-network
    environment:
      - APP_PORT = 3001

      - MYSQL_HOST=food-ordering-foodordering.d.aivencloud.com
      - MYSQL_PORT=27124
      - MYSQL_USER=avnadmin
      - MYSQL_PASSWORD=AVNS_mkYFf1c8TSqmk5jeleL
      - MYSQL_DATABASE=defaultdb

      - JWT_SECRET="SE346@P21"
      - JWT_EXPIRES_IN=3600s

      - MAILTRAP_HOST=sandbox.smtp.mailtrap.io
      - MAILTRAP_PORT=2525
      - MAILTRAP_USER=e5730f994d0ef2
      - MAILTRAP_PASS=ec10874e2fbfb3
      - MAIL_FROM=foodbooking@gmail.com

      - RABBITMQ_URL=amqps://wdxhqejw:UO9KrlPMoEHYBeOaDNGoCf1AklWXG6NX@armadillo.rmq.cloudamqp.com/wdxhqejw
      - RABBITMQ_NAME=foodordering
      - RABBITMQ_QUEUE_OTP=otp_authentication
      - RABBITMQ_QUEUE_PUSH=push_notification
      - RABBITMQ_QUEUE_PAYMENT=payment_completed
      - RABBITMQ_QUEUE_ORDER_STATUS=order_status
      - REDIS_QUEUE=redis_service

      - CLOUDINARY_NAME=daxxuqogj
      - CLOUDINARY_API_KEY=436316462347214
      - CLOUDINARY_API_SECRET=5oIMlaDECvys_-OGGZt-Irk8_Hw

      - PAYPAL_CLIENT_ID=AcbmqATxBNYSNscNEdozkx40CnBkjNSsNpwiF2vpvM-GccRXEUg3o2fCmssSGsWyk6klbEAm5AFaivNs
      - PAYPAL_CLIENT_SECRET=EJ4g2fCwRj7YrjWyGG9CX2uqar1mugs7wyed4tDG2CzpxuhF7x5JUP2-BbZos-JYC4p3G-pkdH2RA8Nm
      - PAYPAL_API=https://api-m.sandbox.paypal.com
      - PAYPAL_SUCCESS_URL=http://nestjs:3001/payment/success
      - PAYPAL_CANCEL_URL=http://nestjs:3001/payment/cancel

      - GOONG_MAP_API_KEY=17Xx1Jgxz67PVs7UndcjIjZSeNpWYt0EoiUkCJof
      - GHN_TOKEN=a991b775-0700-11f0-9d1d-02fc1ab0266e

      - REDIS_HOST=redis-16975.crce194.ap-seast-1-1.ec2.redns.redis-cloud.com
      - REDIS_PORT=16975
      - REDIS_ENABLE=true
      - REDIS_TTL=30000
      - REDIS_PASSWORD=8f1e0c4a-2b3d-4a5b-9c7d-6f2e0f1a3b5c
      - REDIS_USERNAME=default
      - REDIS_DB=FoodOrderingRedis

      - FIREBASE_PROJECT_ID=food-ordering-app-66aa8
      - FIREBASE_CLIENT_EMAIL=firebase-adminsdk-fbsvc@food-ordering-app-66aa8.iam.gserviceaccount.com
      - FIREBASE_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQClZO2pRxUrNNEM\nEgT7kVpBvsgQDdu6AUbvwD0jfjNvaXamQThWo+jUxeVxomkj11+5ihJxNBQNLZnf\nJeaYx3s+b59qazykmN45RRCNQ1COMdYGikm2bQUjwGf5PmNxNBliptMmliwcx9f3\nfX8IRKf0ylI3QWUhIpyvvsqrQQjLyHou4NvJEqDPA5HJ8IP08McliGNdbgkQggSL\n2KDCC3kmSDueYu5PiqohtDKUrCQxVmQoRKLmvEzBzhvhTLZchdEXKtIERtRInFTK\nJ4cRF5M8iYDkKsRJzCVTdcVjBdRmjPJEJOmG2dlJytIlk0uLp/PnY/ZnLKiUMdso\nznnWI+h9AgMBAAECggEAHCWF8IXhS14MqWIzqOA+nOurvletagUnnkt33B9w/2fS\nQk7dGJmCWRtohaMfA3N2neuqYct8EhYNlpUrnhpsld6HIaQoSNafEt33CCNJhTlj\n8+76xmndMw1eZGNCpxQ3sbs0Od/al/dGgJ7BzJVqg9Uekrq1TCNIyPvOH8DMj2lD\nn+fgUzTuPN0QLcIjSEZH6AUc53ZryMjg2gS0lQJh+DA/s0cWoN6SyPcT3Ln78NwB\n9VK03TkA0IJgeQSug1X3v1R/3UBPFebUWJaTBFp5pKLn4eorp4lsXu9QnxHlsdke\nzSpI31qn0hWKfFomur8ajJUG4N3JZbVRXup4mlg/oQKBgQDPjYMwqGtqF05bkIbU\nz/wZFJONP7Fnvwhh+8p6xnVTmHLDYpRslfCZXnVNZcco/hN1oXtbUnIUeBwYZDrH\nf5vRyKSC986Q6W0OxbwDa14j3icA2ffZVO1mACZSvDgtc1f5uPzdU+ZdA3yuVfJC\n4235UsWItMjMUisOTmQQdMZlSQKBgQDMADK3nMG2/H4TnVJubdfSww1ImEcmDa2n\n6cpgPsWpLdZj7kBzLGkRWNwJ4+i1FLwJ1WL4wjkMwZ9x1vmot30maaCEZfYb+pTh\n/9qkGu+4Vc9+h26Jr7uEEwZfzEZBS4NdcMIKpX/vBmT9C4vBC29oX8oq0Bl8L7F6\n+QoKhJRNlQKBgAlNJTj0A0RQ4REXbANzgq+5DVfCJ/gnRn/lodBYvn9NkK8S5uXq\n3kpxQj6CticvI74cy4NvMW+bZl7tdvjjzh7bqAu6gUZbP6ju0Zsxn5lp5kOSgRn7\nRVxR22XPy5C135ZwZNyiWuuGMXs6nM3ElXQb8oBK4cjOUeGlP7TBFvcJAoGACTnp\nEUzRpgj9Wr2+wKfPHwUbULEyZpIvzGxSbs/n+KLOE27vE0Zq6hHuwbPBDo+FgZxZ\nAY8nLWCEaY2jdPH3gwk77UD/RHysxxvfM5TUSq322G4fnbKI9Iw3uZVvh/x2UH+N\nBxY9Fv5fCuK+y1hNDZdneVA4FtnBWSJyRc+BNZECgYA+cenzD9FjhTe5IkbnNZ9Q\nM82ifcN419rVLWnDUgcaMPAx1kLWeb/oMJkvZauENYxnw+M1NaPwo/Y3EUXiaXAe\npob0k81xmrYnE0fUVS3qWlGLsjvW4zYfe6RJu2Sa15kQbR86U6SqzXijiuOejAxF\nZqR7eu6xh8VfoMLgK28lOA==\n-----END PRIVATE KEY-----\n

      - FASTAPI_URL=http://fastapi:8000

networks:
  app-network:
    driver: bridge
